# Generated by Django 4.1 on 2022-09-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0002_workorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='desc',
            new_name='task_desc',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='name',
            new_name='task_name',
        ),
    ]
